services:
  - type: web
    name: weyn-tools
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --threads 4 main:app
    envVars:
      - key: SESSION_SECRET
        generateValue: true
      - key: ADMIN_PASSWORD
        sync: false
